[tasks.default]
alias = "build-all"

[tasks.build-all]
description = "Build everything: hypervisor, evaluation binaries, and bootloaders"
dependencies = ["build-hikami", "build-bootloaders"]

[tasks.build-emulation-binaries]
description = "Build emulation evaluation binaries for both qemu and megrez"
script = [
  "nix develop ./evaluation --command bash -c 'cd evaluation/emulation_overhead && cargo make build_megrez && cargo make build_qemu'",
  "nix develop ./evaluation --command bash -c 'cd evaluation/timer_interrupt_overhead && cargo make build'",
  "nix develop ./evaluation --command bash -c 'cd evaluation/external_interrupt_overhead && cargo make build'",
]

[tasks.link-guest-images]
description = "Link built emulation binaries to hikami guest image directory"
dependencies = ["build-emulation-binaries"]
script = [
  "mkdir -p hikami/guest_image/megrez",
  "mkdir -p hikami/guest_image/qemu",
  "ln -sf ../../../evaluation/emulation_overhead/target/riscv64imac-unknown-none-elf/release/emulation_overhead hikami/guest_image/megrez/emulation_eval",
  "ln -sf ../../../evaluation/emulation_overhead/target/riscv64imac-unknown-none-elf/release/emulation_overhead hikami/guest_image/qemu/emulation_eval",
  "ln -sf ../../../evaluation/timer_interrupt_overhead/target/riscv64imac-unknown-none-elf/release/timer_interrupt_overhead hikami/guest_image/megrez/timer_eval",
  "ln -sf ../../../evaluation/timer_interrupt_overhead/target/riscv64imac-unknown-none-elf/release/timer_interrupt_overhead hikami/guest_image/qemu/timer_eval",
  "ln -sf ../../../evaluation/external_interrupt_overhead/target/riscv64imac-unknown-none-elf/release/external_interrupt_overhead hikami/guest_image/megrez/external_eval",
  "ln -sf ../../../evaluation/external_interrupt_overhead/target/riscv64imac-unknown-none-elf/release/external_interrupt_overhead hikami/guest_image/qemu/external_eval",
]

[tasks.build-hikami]
description = "Build the Hikami hypervisor"
dependencies = ["link-guest-images"]
script = ["nix develop ./hikami --command cargo make build-hikami-internal"]

[tasks.build-hikami-internal]
description = "Internal task to run cargo build for hikami"
command = "cargo"
args = ["build", "--release", "--features", "identity_map"]
cwd = "hikami"

[tasks.build-u-boot]
description = "Build U-Boot for Megrez"
script = [
  "nix develop ./rockos-u-boot --command bash -c 'cd rockos-u-boot && cargo make install'",
]

[tasks.build-opensbi]
description = "Build and sign OpenSBI with U-Boot payload"
dependencies = ["build-u-boot"]
script = [
  "nix develop ./rockos-opensbi --command bash -c 'cd rockos-opensbi && cargo make sign'",
]
[tasks.build-bootloaders]
description = "Alias for building both U-Boot and OpenSBI"
alias = "build-opensbi"

[tasks.install]
description = "Install built artifacts (bootloader and hypervisor) to SD card"
dependencies = ["build-all"]
script = [
  "echo \"Installing to ${DEVICE}1...\"",
  "sudo mount ${DEVICE}1 /mnt",
  "sudo cp rockos-opensbi/sign/preload/bootloader_secboot_ddr5.bin /mnt/",
  "sudo cp hikami/target/riscv64imac-unknown-none-elf/release/hikami /mnt/hikami.elf",
  "ls -l /mnt/",
  "sudo umount /mnt",
  "echo \"Installation complete.\"",
]

[tasks.clean]
description = "Clean all built binaries"
script = [
  "rm -rf evaluation/emulation_overhead/target",
  "rm -rf evaluation/timer_interrupt_overhead/target",
  "rm -rf evaluation/external_interrupt_overhead/target",
  "rm -f hikami/guest_image/megrez/emulation_eval",
  "rm -f hikami/guest_image/qemu/emulation_eval",
  "rm -f hikami/guest_image/megrez/timer_eval",
  "rm -f hikami/guest_image/qemu/timer_eval",
  "rm -f hikami/guest_image/megrez/external_eval",
  "rm -f hikami/guest_image/qemu/external_eval",
  "rm -f hikami/guest_image/initrd",
  "cd hikami && cargo clean",
  "cd rockos-u-boot && make clean",
  "cd rockos-opensbi && make clean",
  "rm -f rockos-opensbi/u-boot.bin rockos-opensbi/u-boot.dtb",
  "rm -f rockos-opensbi/sign/preload/fw_payload.bin rockos-opensbi/sign/preload/bootloader_secboot_ddr5.bin",
]
